Updated version numbers in pom.xml

diff --git a/.github/workflows/deploy_to_maven_central.yml b/.github/workflows/deploy_to_maven_central.yml
--- a/.github/workflows/deploy_to_maven_central.yml
+++ b/.github/workflows/deploy_to_maven_central.yml
@@ -33,7 +33,7 @@ jobs:
         uses: actions/cache@v4
         with:
           path: ~/.m2/repository/*
-          key: "${{ runner.OS }}-maven-${{ hashFiles('**/pom.xml') }}"
+          key: "${{ runner.OS }}-maven-${{ hashFiles('**/pom.xml') }}-tag-release"
 
       - name: Configure Git User
         run: |
@@ -77,19 +77,28 @@ jobs:
       packages: write
     with:
       COMMIT_ID: ${{ needs.tag-release.outputs.TAG }}
+      VERSION: ${{ needs.tag-release.outputs.VERSION }}
       FOR_RELEASE: true
   deploy:
-    needs: [ build ]
+    needs: [ tag-release, build ]
     name: Deploy
     runs-on: ubuntu-latest
     outputs:
       ID: ${{ steps.upload.outputs.ID }}
     steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.ref }}
+
+      - name: Configure Git User
+        run: |
+          git config user.email "cowwoc2020@gmail.com"
+          git config user.name "Gili Tzabari"
+
       - name: Download bundles
         uses: actions/download-artifact@v4
         with:
-          merge-multiple: true
-          path: "${{ github.workspace }}/bundles/io/github/cmake-maven-plugin"
+          path: "${{ github.workspace }}/bundles"
 
       - name: Generate metadata
         shell: bash
@@ -109,6 +118,20 @@ jobs:
           # Remove the temporary key file immediately after import
           shred --remove "${GPG_KEY_FILE}"
           
+          # Based on https://unix.stackexchange.com/a/743986/60809
+          FINGERPRINT=$(gpg --list-secret-keys --with-colons | awk -F: '
+            $1 == "sec" {found = 1; next} 
+            found && $1 == "fpr" {print $10; exit}
+          ')
+          
+          if [ -z "${FINGERPRINT}" ]; then
+            echo "Error: Could not parse the secret key's fingerprint"
+            exit 1
+          fi
+          
+          # Set the secret key as default
+          echo "default-key ${FINGERPRINT}" >> ~/.gnupg/gpg.conf
+          
           # Define the temporary file location for the passphrase
           export GPG_PASSPHRASE_FILE="$(mktemp)"
 
@@ -118,22 +141,25 @@ jobs:
           # Setup a cleanup trap to remove the key after the job completes
           cleanup_gpg()
           {
-            # Based on https://unix.stackexchange.com/a/743986/60809
-            FINGERPRINT=$(gpg --list-secret-keys --with-colons | awk -F: '
-              $1 == "sec" {found = 1; next} 
-              found && $1 == "fpr" {print $10; exit}
-            ')
-            if [[ -n "${FINGERPRINT}" ]]; then
-              gpg --batch --yes --delete-secret-keys "${FINGERPRINT}"
-              gpg --batch --yes --delete-keys "${FINGERPRINT}"
-            fi
+            gpg --batch --yes --delete-secret-keys "${FINGERPRINT}"
+            gpg --batch --yes --delete-keys "${FINGERPRINT}"
             shred --remove --force "${GPG_PASSPHRASE_FILE}"
             unset GPG_PASSPHRASE_FILE
           }
           trap cleanup_gpg EXIT
           
+          # Create the expected directory structure
+          mkdir -p publish/
+          mv bundles/pouch-bundle/.m2/repository/* publish/
+          
+          VERSION=${{ needs.tag-release.outputs.VERSION }}
+          rm -rf docs/api/${VERSION}
+          mkdir --parents docs/api/${VERSION}
+          mv bundles/pouch-bundle/work/pouch/pouch/docs/api/${VERSION} docs/api/${VERSION}
+          rm -rf bundles
+
           # Sign and generate checksums for all JAR and POM files
-          cd bundles 
+          cd publish/
           find . -type f \( -name "*.jar" -o -name "*.pom" \) -exec sh -c '
             for file; do
               cat "${GPG_PASSPHRASE_FILE}" | gpg --batch --pinentry-mode loopback --passphrase-fd 0 --yes \
@@ -149,22 +175,14 @@ jobs:
           cleanup_gpg
           trap - EXIT
 
-          zip -r "../cmake-maven-plugin-${{ needs.tag-release.outputs.VERSION }}.zip" .
-
-      # Must quote exclamation mark on bash: https://stackoverflow.com/a/27177197/14731
-      - name: Generate documentation
-        run: |
-          ./mvnw --batch-mode -V -e -pl '!dropwizard,!jersey' verify javadoc:aggregate
-          VERSION=${{ needs.open-release.outputs.VERSION }}
-          rm -rf "docs/api/${VERSION}"
-          mkdir --parents "docs/api/${VERSION}"
-          mv target/reports/apidocs/* "docs/api/${VERSION}"
+          zip -r "../pouch-${{ needs.tag-release.outputs.VERSION }}.zip" .          
+          cd ..
 
       - name: Commit documentation
         run: |
-          git checkout ${{ github.ref_name }} -f
-          git add "docs/api/${{ needs.open-release.outputs.VERSION }}"
-          git commit -m "Publishing documentation for version ${{ needs.open-release.outputs.VERSION }}"
+          VERSION=${{ needs.tag-release.outputs.VERSION }}
+          git add docs/api/${VERSION}
+          git commit -m "Publishing documentation for version ${VERSION}"
           git push
 
       - name: Upload bundle
@@ -180,8 +198,8 @@ jobs:
           
           ID=$(curl --request POST --show-error --fail \
           --header "Authorization: Bearer ${BEARER_TOKEN}" \
-          --form "bundle=@cmake-maven-plugin-${VERSION}.zip" \
-          --form "name=cmake-maven-plugin-${VERSION}" \
+          --form "bundle=@pouch-${VERSION}.zip" \
+          --form "name=pouch-${VERSION}" \
           --form "publishingType=USER_MANAGED" \
           https://central.sonatype.com/api/v1/publisher/upload)
           
